backend:
  name: git-gateway
  branch: main

media_folder: "public/media"
public_folder: "/media"

collections:
  - name: "music"
    label: "Music"
    folder: "src/content/music"
    slug: "{{sortOrder}}-{{slug}}"
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Release Year", name: "year", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Item Number", name: "sortOrder", widget: "number" }
  - name: "music videos"
    label: "Music Videos"
    folder: "src/content/music-videos"
    slug: "{{sortOrder}}-{{slug}}"
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Release Year", name: "year", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Item Number", name: "sortOrder", widget: "number" }
  - name: "film"
    label: "Film"
    folder: "src/content/film"
    slug: "{{sortOrder}}-{{slug}}"
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Release Year", name: "year", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Item Number", name: "sortOrder", widget: "number" }
  - name: "press"
    label: "Press"
    folder: "src/content/press"
    slug: "{{sortOrder}}-{{slug}}"
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Release Year", name: "year", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Item Number", name: "sortOrder", widget: "number" }
  - name: "writing"
    label: "Writing"
    folder: "src/content/writing"
    slug: "{{sortOrder}}-{{slug}}"
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Release Year", name: "year", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Item Number", name: "sortOrder", widget: "number" }
  - name: "bio"
    label: "Bio"
    folder: "src/content/bio"
    slug: "bio-details"
    create: true
    delete: true
    fields:
      - { label: "Site Bio", name: "bio", widget: "string" }
      - { label: "Bio Section Title 1", name: "bioHeader1", widget: "string" }
      - { label: "Bio Section 1", name: "bioBody1", widget: "text" }
      - { label: "Bio Section Title 2", name: "bioHeader2", widget: "string" }
      - { label: "Bio Section 2", name: "bioBody2", widget: "text" }
      - { label: "Bio Image 1", name: "bioImage1", widget: "image" }
      - {
          label: "Bio Image 1 Alt Text ",
          name: "bioImageAlt1",
          widget: "string",
        }
      - { label: "Bio Image 2", name: "bioImage2", widget: "image" }
      - {
          label: "Bio Image 2 Alt Text ",
          name: "bioImageAlt2",
          widget: "string",
        }
      - { label: "Bio Image 3", name: "bioImage3", widget: "image" }
      - {
          label: "Bio Image 3 Alt Text ",
          name: "bioImageAlt3",
          widget: "string",
        }
  - name: "pics"
    label: "Site Images"
    folder: "src/content/pics"
    slug: "main-pics-details"
    create: true
    delete: true
    fields:
      - { label: "Site Images", name: "siteImages", widget: "string" }
      # - { label: "Site Background", name: "siteBg", widget: "image" }
      - { label: "Main Header Image", name: "mainPic", widget: "image" }
      - { label: "Contact Me Image", name: "contactPic", widget: "image" }
