backend:
  name: git-gateway
  branch: main

media_folder: "public/media"
public_folder: "/media"

collections:
  - name: "music"
    label: "Music"
    folder: "src/content/music"
    slug: "{{sortOrder}}-{{slug}}"
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Release Year", name: "year", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Item Number", name: "sortOrder", widget: "number" }
  - name: "music videos"
    label: "Music Videos"
    folder: "src/content/music-videos"
    slug: "{{sortOrder}}-{{slug}}"
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Release Year", name: "year", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Item Number", name: "sortOrder", widget: "number" }
  - name: "film"
    label: "Film"
    folder: "src/content/film"
    slug: "{{sortOrder}}-{{slug}}"
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Release Year", name: "year", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Item Number", name: "sortOrder", widget: "number" }
  - name: "press"
    label: "Press"
    folder: "src/content/press"
    slug: "{{sortOrder}}-{{slug}}"
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Release Year", name: "year", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Item Number", name: "sortOrder", widget: "number" }
  - name: "writing"
    label: "Writing"
    folder: "src/content/writing"
    slug: "{{sortOrder}}-{{slug}}"
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Release Year", name: "year", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Item Number", name: "sortOrder", widget: "number" }
  - name: "bio"
    label: "Bio"
    folder: "src/content/bio"
    slug: "{{body1}}"
    create: true
    delete: true
    fields:
      - { label: "Body1", name: "body1", widget: "string" }
      - { label: "Body2", name: "body2", widget: "string" }
      - { label: "Image1", name: "image1", widget: "image" }
      - { label: "Image2", name: "image2", widget: "image" }
      - { label: "Image3", name: "image3", widget: "image" }
